//auth actions

export const authActionTypes = {
	LOGIN: "LOGIN",
	IS_LOGING_IN: "IS_LOGING_IN",
	LOGIN_COMPLETE: "LOGIN_COMPLETE",
	LOGOUT: "LOGOUT",
	AUTH_ERROR: "AUTH_ERROR",
	SIGNUP: "SIGNUP",
	LOADING: "LOADING",
	LOADING_COMPLETE: "LOADING_COMPLETE",
	SIGNUP_ERROR: "SIGNUP_ERROR",
	NETWORK_ERROR: "NETWORK_ERROR",
	TYPING: "TYPING",
	RESET_PASSWORD: "RESET_PASSWORD",
	GET_ORGANIZATION: "GET_ORGANIZATION",
	GET_ALL_ORGANIZATIONS: "GET_ALL_ORGANIZATIONS",
	SWITCH_ORGANIZATION: "SWITCH_ORGANIZATION",
};
