export const GET_DASHBOARD_STATS = "GET_DASHBOARD_STATS";
export const LOADING_DASHBOARD = "LOADING_DASHBOARD";
export const LOADING_DASHBOARD_COMPLETE = "LOADING_DASHBOARD_COMPLETE";
export const GET_ACTIVITY_LOG = "GET_ACTIVITY_LOG";
export const LOADING = "LOADING";
export const LOADING_COMPLETE = "LOADING_COMPLETE";
export const GET_CHART_DATA = "GET_CHART_DATA";
